### ISSUE TITLE
Ambiguous option handling

### ISSUE THREAD

**Issue by markdwood** [commandlineparser/commandline#202]
If I have a string-valued option whose short (single character) letter is, say, 't', and I have another option whose long name is, say "time", and if one forgets to use a double dash, the option "-time" is interpreted as 't' with a value of "ime".  

This can lead to some frustrating errors.  What is the recommended way to handle this sort of ambiguity?  

Perhaps a mechanism for requiring spaces after short option names?  Or some mechanism to flag this as potentially ambiguous?

**Comment by ericnewton76** [comment]
Hmmm, thats interesting...  I wasnt aware it would interpret -time as -t ime.  

It's not really ambiguous, because --time should be treated 100% differently than -time, although I'm not exactly sure atm how to address that.  

I believe you're right that a space should be enforced unless explicit in the options config.  The scenario is similar to command like ```git log -n5``` which already exists by convention.  So if there were a c# git program, you'd specify support for not having a space for the --lines shorthand '-n' and the help text could specifically mention that.

**Comment by nemec** [comment]
The library was designed to conform to (most of, at least) the [rules of getopt](https://www.gnu.org/software/libc/manual/html_node/Example-of-Getopt.html#Example-of-Getopt), a Linux/Unix CLI parser.

Not only can `-time` be interpreted as `-t ime`, depending on how your Options are set up it could also be parsed as `-t -i -m -e`:

```csharp
void Main()
{
	Parser.Default.ParseArguments<Options>("-time hello".Split())
		.WithParsed(o => o.Dump());
}

class Options
{
	[CommandLine.Option('t')]
	public bool Ta { get ; set; }
	
	[CommandLine.Option('i')]
	public bool Ia { get; set; }

	[CommandLine.Option('m')]
	public bool Ma { get; set; }

	[CommandLine.Option('e')]
	public string Ea { get; set; }
}
```

In theory, this allows you to take a shortcut when you know your use is unambiguous but leave you an explicit fall-back (e.g. `-t[space]ime`) in case of ambiguity. However, I definitely understand how someone new to the library could be confused when they don't understand that there _is_ ambiguity in the first place.

**Comment by markdwood** [comment]
The problem is that if a user types, say "-time" when they should have typed "--time", the behavior will not be as they expect.  I would like a way to catch this operator error.

**Comment by ericnewton76** [comment]
At first glance, I can't think the any way to know you didnt intend ```-t -i -m -e``` if you dont use the double-dash ```--time``` 

A better option (pun intended) might be to break up the options into separate verbs?

**Comment by VladCananau** [comment]
> At first glance, I can't think the any way to know you didnt intend `-t -i -m -e` if you dont use the double-dash `--time`

Unless the shorthand options -i -m and -e actually exist in his verb, then I think you can safely conclude that he didn't intend `-t -i -m -e`, right?

I've hit the same issue at first time usage of the library. It's actually a rather dangerous "feature". My command was `creatething -id 123` where instead of creating a thing with id '123' it goes ahead 
and creates a thing with id 'd' and ignores the '123' token. Btw, even with IgnoreUnknownArguments set to false '123' is ignored. I would have expected at least that to safeguard me and fail parsing.
