### ISSUE TITLE
Bug with \"

### ISSUE THREAD

**Issue by sybaris** [commandlineparser/commandline#226]
Hello

The following command line is KO : 
`-F "d:\toto\"`
result is : Folder = `d:\toto"`
Note the quote at the end of the string --> bug

Note also that the following command line is OK : 
`-F "d:\toto"`
result is : Folder = `d:\toto`

Here the example code :
 ```
       static void Main(string[] args)
        {
            ParserResult<Options> result = CommandLine.Parser.Default.ParseArguments<Options>(args);
            result.WithParsed<Options>(opts => 
                Console.WriteLine("Folder = "+opts.Folder)
                );
        }
    class Options
    {
        [Option('F', "Folder", HelpText = "indicate a folder")]
        public string Folder { get; set; }
    }
```

Regards
Sybaris
![result](https://user-images.githubusercontent.com/11009997/35012221-5baa9be8-fb09-11e7-8090-e0d907aebcf4.jpg)

**Comment by nemec** [comment]
This is caused by .NET itself and not something we can control. If you print out the values in `args` you will see that your trailing slash disappeared and a lone quote mark is present instead. Backslash is an escape character for double quotes.

You have a few options:
1. Remove the trailing slash when calling the program (most if not all path functions will accept both, and you should be using `Path.Combine` to join paths which won't care whether there is a trailing slash)
2. Use forward slashes instead (path functions will generally accept both)
3. Escape the backslash in your input rather than the quote with an extra backslash: `-F "d:\toto\\"` 

https://stackoverflow.com/questions/17830545/passing-filepath-into-mainstring-args-not-working
https://stackoverflow.com/questions/22280109/file-path-as-command-line-argument
https://stackoverflow.com/questions/653563/passing-command-line-arguments-in-c-sharp

**Comment by sybaris** [comment]
Hi

Thanks for this information.
I was not aware of this behavior and now I understand better...

Regards
Sybaris

**Comment by fairking** [comment]
Why then the `\t` (in `-F "d:\toto\"`) is not being escaped? I think this is weird unpredictable behaviour must be fixed by microsoft.
