### ISSUE TITLE
Build issue - invalid snk file ?

### ISSUE THREAD

**Issue by martinsmith1968** [commandlineparser/commandline#254]
I can't build the current master branch - I get `"csc. exe" exited with code -532462766.`
If i build from the command line using msbuild I can see : `"Unhandled Exception: System.Security.Cryptography.CryptographicException: Bad Data."`

Trying to verify the CommandLine.snk using : `sn -tp CommandLine.snk `
Gives: `Failed to convert key to token -- Invalid assembly public key.`

I can regenerate the .snk file using `sn -k CommandLine.snk` and remove the Public Key info from AssemblyInfo InternalsVisibleTo and then both projects build ok.

The .snk file in the repo is 595 bytes and thus 1 byte shorter than the generated one.

From the git log it looks like the .snk file hasn't changed in years, yet does not appear to be valid. Am I missing something? Is this file intentionally crippled in the repo for security? 

I have some features I'd like to develop and submit for addition to the project. I can progress for now using the changes I mention above but it would be nice to not have to make them.

I'm using VS2017 Pro.

Thanks!

**Comment by ericnewton76** [comment]
Hey @martinsmith1968 

Thanks in advance for helping with the library.  I guess just use your regenerated key, there must be some kind of corruption of that particular file in your git repo.  Might try just re-cloning, and see if that fixes it.  Not sure about that error because it appears to build fine elsewhere.

Btw, you'll still need your (new) public key info with an InternalsVisibleTo for the tests to work, I believe.

Again, thanks in advance for any future additions you make!

**Comment by ElijahReva** [comment]
Same issue for me vs2017 on Windows Server 2008

**Comment by martinsmith1968** [comment]
Phew, I thought it was just me!
I wonder if it's to do with the GIT setting about line endings? It can convert between CRLF and Unix during pull/push

**Comment by ElijahReva** [comment]
@martinsmith1968 Nah :(
I've used `git config --global core.autocrlf false` before cloning the repo and it still reporting `Bad Data` error.

**Comment by moh-hassan** [comment]
It's fixed since v2.5
