### ISSUE TITLE
Argument starting with hyphen character (written between quotation marks) is ignored: "-", "-aaa"

### ISSUE THREAD

**Issue by luissagasta** [commandlineparser/commandline#300]
Hello.
When passing an argument with a value that starts with hyphen, it is ignored.

Example:

_mycmd.exe verb -o "-"_
_ERROR(S):_
_Option 'o' has no value._

_mycmd.exe verb -o "-a"_
_ERROR(S):_
_Option 'a' is unknown._
_Option 'o' has no value._

How could I pass an argument that starts with hyphen?
Thank you.

Regards.

**Comment by moh-hassan** [comment]
>How could I pass an argument that starts with hyphen?

I did a test for cases of argument that starts with hyphen '-'  using V2.x and it's working fine and parser can differentiate between '-' as an option and '-' as part of argument value without errors.

This is Working:


		//define Verb Class
		[Verb("verb", HelpText = "Test Argument starting with hyphen character (written between quotation marks)")]
		class Verb 
		{ 
			[Option('o')]
			public string MyOption { get; set; } 
			
			//Extra option 'a' for sensing if parser can differentiate options mixed with dash '-' 
			[Option('a')]
			public string MyOption2 { get; set;} 
		}


		Parser.Default.ParseArguments<Verb>(args)
						  .WithParsed<Verb>(opts => {RunAddOption(opts);})		
						  .WithNotParsed(errs => {});

[Working Demo: ](https://dotnetfiddle.net/xV1GNL)
	
>Output Result
Args: ' verb -o "-" ' WithParsed  value= "-"
Args: 'verb -o "-a" ' WithParsed  value= "-a"
Args: 'verb -o "-aaa" ' WithParsed  value= "-aaa"
Args: 'verb -o "-aaa" -a xyz' WithParsed  value= "-aaa"

**Comment by nemec** [comment]
@moh-hassan `String.Split` is a useful approximation for argument splitting but it is _not_ the same process that an application's CLI arguments go through when provided to the Main args. You put quotes around the `-a` but when the CLR splits the parameter string it takes everything inside the quotes, _removes the quotes_, and then puts the remaining part as an entry in the array. Your sample leaves the quotes in the array, which is why your test worked.

@luissagasta by that same token, no matter how you quote the value, there is no way for a C# program to tell the difference between `verb -o -a` and `verb -o "-a"` - you can print the args array yourself and see that there is no difference. Knowing that `-o` consumes a value, it should be possible to assume `-a` is the value if it follows `-o`, but it isn't something the library does today.

One thing you could do is create a new parser instance with EnableDashDash set

```
new Parser(c =>
{
	c.EnableDashDash = true;
})
```
This lets you use `--` to explicitly tell the parser to stop parsing options that begin with `-`. I tested and the following CLI parameter string seems to assign `-a` correctly: `-o -- -a`

**Comment by moh-hassan** [comment]
**@nemec ,** You are right, CLR removes the quotes, and then puts the remaining part as an entry in the array. 

I build a console application to use CLR splitter  without my splitting method, and passed the parameters via cmd screen and Parser raises the error `Option 'o' has no value`

Your suggestion of using double dash --  is working fine

**@luissagasta,** I find the solution provided by @nemec  can solve your problem.
