### ISSUE TITLE
Good work - a simpler example to get started would be much appreciated

### ISSUE THREAD

**Issue by sdg002** [commandlineparser/commandline#341]
Very handy library. It took me a little while to figure out the structure of the command line syntax that is expected using the default settings.

I was following the  [Wiki](https://github.com/commandlineparser/commandline/wiki) and began with this:
`
MyApp.exe -option1 value1 -option2 value2
`
However, after a bit I realized that the expected syntax is
`
MyApp.exe --option1 value1 --option2 value2
`

Thanks,
Sauabh

**Comment by mbedded** [comment]
Hi Saubah,
single dash is used for the abbreviation form like"-u" instead of "--userName". It may be confusing if you're not that familiar with Linux. There you have a lot of double dashes :)

From my point of view the wiki is clear about the calls in the beginning:
https://github.com/commandlineparser/commandline/wiki#option-attribute

There you have only one argument which is called by app --key=value (space instead of = is working, too).

What is you expectation here? Should the double-dash be highlighted somewhere or what could be improved? If you're stuck, you can use MyApp --help which will display how to set the parameters correctly
