### ISSUE TITLE
Please help - real world requirement

### ISSUE THREAD

**Issue by The-Futurist** [commandlineparser/commandline#373]
Hi, please look at this:

command line expectations

`zone `string required allow (qa1, uat1, dev1, prod)

`update `bool defaults to false

`log `bool defaults to false

`mode `string required allow (ftp, file)

IN FILE MODE

files IEnumerable<string> required allow (one or two paths) files must exist

IN FTP MODE

dates IEnumerable<DateTime> required (one or two date strings) first date (reading from left to right) must be earlier than second date, second date cannot be > todays date

Examples

`application --zone=qa1 --update --log --mode=ftp 2018-11-05`

`application --zone=qa1 --update --log --mode=ftp 2018-11-05 2018-11-18`

`application --zone=prod --update --log --mode=file C:\downloads\file-01.csv`

`application --zone=dev1 --update --log --mode=file C:\downloads\file-01.csv C:\downloads\file-05.csv `

It would be most helpful of you could explain how one might implement this.

Thanks

**Comment by nemec** [comment]
Hey @Korporal here are my thoughts on your requirements, with a small tweak that would reduce the amount of post-parsing validation code.

* Instead of making `mode` an option, make it a verb. This will let you define separate options for File and FTP
  * CLI would look like `application file --zone=dev1 c:\file.csv [...]` and `application ftp --zone=dev1 2018-11-05 [...]`
  * To reduce duplication, make a base class for options common to both verbs, then separate classes for File and Ftp that implement unique options.
  * Without verbs the parser won't know whether it should expect a list of dates or files. You'll have to parse both to an `IEnumerable<string>` and do the rest of the logic yourself.
* `update` and `log` will be fine as bools and work as you expect.
* `zone` should probably be an enum, otherwise you will have to validate the allowed list of choices yourself.
* In FTP mode, an `IEnumerable<DateTime>` should correctly support your list of dates - use OptionAttribute's Min and Max properties to restrict the allowed number of dates to 1-2.
* Additional validation, like file exists or date1 < date2 is not supported in the framework. Once the values are parsed, you'll have to check that and raise your own errors as needed.

Hope this helps some.

**Comment by The-Futurist** [comment]
@nemec - Hi and thanks, I'll read your comments more closely later, but I do appreciate the prompt reply.
