### ISSUE TITLE
Feature requests, some more options

### ISSUE THREAD

**Issue by GiganteX** [commandlineparser/commandline#444]
Greetings!

Some thoughts after having experimented with this package today:

1. I like my options without hyphen signs, is there any way I could get that? So I can have usage like: 
> myprogram verb file=filename.txt verbose simulate

2. Smart verb and option shortening. Let's say I have verbs "replace" and "restore".
I should be able to write "rep" and the code should map it to the "replace" command.
If I write only "re" it should tell me that it can't map it as it matches both "replace" and "restore".

3. possibility to have verbs with two or more words. It should also be able to get shortening by abbreviation. Let's say one possible verb is "restore package" and another is "restore file"
It should be able to get that "rp" matches "restore package". Also "r p" should match, and "res pa" and so on.

4. Multiple alternate names. I might for example want to accept verbs and options in several languages, it would be easy for me if I could just add a list of alternate names. That single-character alternate is not very helpful. Make it a list of strings. :)

5. The character ? should map to "help" . And so should /? and /help and well, a little more accepting of the other "standards" for command line options would be great.

I know, these are not small things and CommandLineParser works as intended for the vast majority of use-cases. ;) Just mentioning these things, maybe you'll think some of it is useful.. :)

**Comment by k4kfh** [comment]
> The character ? should map to "help" . And so should /? and /help and well, a little more accepting of the other "standards" for command line options would be great.

I'm not sure you'll be able to do ``/?`` and ``/help``, because those don't really fit with the syntax CommandLineParser likes (it follows more Linux-ish style, such as ``mycommandlineapp --myflag -a --myvalue=2``). But you may be able to get ``?`` to map to help by adding ``?`` as a verb. I am using the old stable version of this, and unless I am missing something, it would be very easy to do this. It's not a "built-in" solution, but it would be a solution.

> possibility to have verbs with two or more words

I think the intended way to implement it is to have one verb and then have each verb handle "sub-verbs" within itself. You could have a string value argument that takes the second verb word. So you'd have a verb called ``restore`` and that might take a string that gets populated with ``package`` or ``file`` or whatever, and you handle processing that yourself within the ``restoreSubOptions`` class.

> It should also be able to get shortening by abbreviation. Let's say one possible verb is "restore package" and another is "restore file"
It should be able to get that "rp" matches "restore package". Also "r p" should match, and "res pa" and so on.

You're coming from Cisco IOS aren't you? Lol I remember thinking that was the coolest thing when I learned about the shortening. I think in some situations this would be a nice feature, but I imagine it would be somewhat difficult to implement. This might be a good candidate for a PR, but honestly, the ``master`` version of the parser is so unstable right now that I think effort should be put into fixing the gaping holes in the software before adding extra features like this. In particular, the documentation is atrocious, and the help generation is extremely difficult compared to the old version. Not to mention the number of issues open about various general argument parsing problems. The word shortening is a nice idea, I'll admit, perhaps as a setting in the parser that you can toggle on and off, but I think there are bigger fish to fry at the moment personally.
