### ISSUE TITLE
How to pass string with spaces?

### ISSUE THREAD

**Issue by win32nipuh** [commandlineparser/commandline#445]
My app has an argument parameter file path
>myapp -p <path>

When I need to pass a path containing space i do, for example:
>myapp -p "\\srv\my files\"

I see the value:

o.Path = "\\\srv\\my files\""

I.e. , why '"' at the end of string?
What is way to pass string with spaces ?

**Comment by moh-hassan** [comment]
I did a test for your test case and the console return the value without '"' at the end of string as in the figure below:
![demo1](https://user-images.githubusercontent.com/16975310/57962034-6f4a7180-7913-11e9-9d4f-f6bf250ec5ad.PNG)

>What is way to pass string with spaces ?

Enclose the string with double quotation as you did like:

              myapp -p "\srv\my files"

**Comment by ZedZipDev** [comment]
I did as you wrote using 
myapp -p "\srv\my files"

In my WinForms app debugger I see the value:
o.Path = "\\srv\my files""

I use the latest NuGet package.

**Comment by moh-hassan** [comment]
Do you pass the parameters for test in debug  using: `project Properties/ Debug /Application argument`?

Run the application and check the result when passing parameters in the commandline:

                Myformapp   -p "\srv\my files"

**Comment by moh-hassan** [comment]
I tried to repro your issue in winform application in debug mode, but I didn't find '"' at the end of string
Here screenshot in debug mode
![form-debug](https://user-images.githubusercontent.com/16975310/57990761-ee71ae00-7aa9-11e9-805b-bf0aaaec37e4.png)

I passed the arguments to test in debug mode via: project Properties/ Debug /Application argument
Also, in watch screen:
![watch](https://user-images.githubusercontent.com/16975310/57990860-e5351100-7aaa-11e9-8d8c-443733ac9294.png)

This quote is unrelated to CommandLineParser.

**Comment by DS-Kurt-Boberg** [comment]
We have an application exhibiting this same behavior.  The root cause is how Windows parses command-line arguments: a double-quoted path with spaces that ends in a directory will end with a trailing slash.  This escapes the closing double quote in the Windows argv parser.  I suspect the example given here is omitting tab-completion of a directory name on the command line.

https://stackoverflow.com/questions/9287812/backslash-and-quote-in-command-line-arguments
https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/
