### ISSUE TITLE
Read switches from file

### ISSUE THREAD

**Issue by deakjahn** [commandlineparser/commandline#447]
It would be a nice addition that I saw already somewhere: if there is an item starting with a @ on the command line, it's considered to be a config file to contain switches and its contents are read and included. I added it for myself with a very small modification, although it might be worked into the whole package in a nicer way for sure:

in InstanceBuilder.Build<T>(), locate the

    var argumentsList = arguments.Memorize();

line (around line 48), and replace it with:

      var argumentsList = new List<string>();
      foreach (string argument in arguments) {
        if (argument[0] == '@') {
          string filename = argument.Substring(1);
          string switches = string.Join(" ", File.ReadAllLines(filename));
          argumentsList.AddRange(switches.Split(new[] { ' ' }));
        }
        else
          argumentsList.Add(argument);
      }

Some more error checking would be required, too, of course.

**Comment by moh-hassan** [comment]
Good idea. There are some considerations:
- Value options that start with "@" can no longer be used, because it will be interpreted by the parser as filename. 
  This can cause problems to the applications already running and using "@" in start of options when upgrade to the new release.
- Help should be modified to support  this feature under the control of some setting  to show/hide file parameter usage. 
- Error handling should be modified to handle file errors(file not exist, file read error,...)

I thinks the feature can be added as an Extension method without the change in the Parser Code base. 
Developers, in the application side, manage the above issues  using custom help.

The Extension method, like:

      public static class CommandLineExtensions
      {
         public static string[] ExpandArgs(this string[] arguments)
         {
            //rest of code
            //Handle file errors
          }
       }
       
Usage:
   
     result = Parser.Default.ParseArguments<Options>(args.ExpandArgs());  


What do you think @ericnewton76?

**Comment by motwok** [comment]
I just like to open the same request.

@moh-hassan 
i agree to your considerations…

But i see no way to handle the Errors or reflect the expansion in Help when you do it this way.
From my point, this should be really done by only modify the settings, so the the two overwrites of the Parser.ParseArguments methodes are the best (from my view) places to add this logic.

Emmo

**Comment by moh-hassan** [comment]
@motwok 
With the extension method solution, developer can create a custom help in his application and add something like:

>Note: If you start the options  with the letter @, the rest should be a filename of switches

Also, he can handle the errors of file (file not exist,..)
So we can add  Extension methods as an extensibility mechanism to the CommandLineParser. 

In case of adding  the feature as built-in method in the Parser and controlled by setting in the [ParserSettings](https://github.com/commandlineparser/commandline/blob/master/src/CommandLine/ParserSettings.cs), help and errors are managed based on this setting. 
Is it right?

**Comment by motwok** [comment]
@moh-hassan 
sure… but i think this Expansion should be integrated… if you have it outside of Parser you "must" do all the the things manually. Sounds like reinventing the wheel for me.

**Comment by moh-hassan** [comment]
Yes, I mean that the extension method is merged and be a part of the package.
Reinventing the wheel should be avoided.
As you prefer that the feature be part of the Parser, no problem for me. 
@deakjahn, can submit PR.
