### ISSUE TITLE
Can't read arguments in Windows Server 2008 R2

### ISSUE THREAD

**Issue by wendellestradairely** [commandlineparser/commandline#472]
When I ran my console app in Windows 10, it works perfectly and was able to read and parse all arguments. But, when I ran the app in Windows Server 2008 R2, it can't read the arguments and says they're missing. Am I missing something? I have no idea how to fix it because I was just using the most simple example in the QuickStart in the docs.
![image](https://user-images.githubusercontent.com/50942719/60935905-f9083100-a2fd-11e9-8c11-4dab38a9cf19.png)

**Comment by moh-hassan** [comment]
Welcome to the Commandlineparser project.
I can't repro the issue because no win 2008R2 is available.

To help fixing the issue:
- What is the commandlineparser version you are using?
- What is  Framework you are compiling to?
- What is dotnet version installed in Win server 2008R2.

Try to run the application as `Admin`.
Can you modify your code and dump the arguments of `Main(args)` before passing to the parser to check if the `args` are passed via Main correctly. The args should match `Environment.GetCommandLineArgs()`.

**Comment by wendellestradairely** [comment]
@moh-hassan Thank you for the feedback. I'm actually using Autofac to build the application dependencies. The arguments were also correct.  I've spent hours debugging and digging into the code and I've figured out that there's something wrong with how I called the ParseArguments method. Maybe it has  something to do with how I resolved the dependencies in Autofac.

```csharp
var builder = new Autofac.ContainerBuilder();
// called ParseArguments here for pre-processing...
builder.Build();
// called ParseArguments here for post-processing
```
I can now close this ticket. I've already found out a solution. It's just weird because it only happens in a Windows Server 2008 R2 production machine that where I deployed the app.

Thanks!
