### ISSUE TITLE
No output for help or version commands.

### ISSUE THREAD

**Issue by AntSwift** [commandlineparser/commandline#516]
When running my application directly from the command line I don't get any output when trying to see help or version information.
When running in debug mode (F5), get the information in the Visual Studio Output window.
When running without debugging (CTRL+F5) I again get no output.

I am adding command line options to a Windows Forms application if that makes any difference.

I am inisialising CommanLine as follows:

```
    var parser = new CommandLine.Parser(x => { x.HelpWriter = null; });
    var parserResult = parser.ParseArguments<CommandLineOptions>(args);

    parserResult.WithParsed((CommandLineOptions opts) =>
    {
        LaunchApp(opts);
    })
    .WithNotParsed(errs =>
    {
        var helpText = HelpText.AutoBuild(parserResult, h => h, e => e);
        Console.WriteLine(helpText);
    });
```

I am using version 2.6.0 installed from NuGet running on .net Framework 4.5.

**Comment by moh-hassan** [comment]
Console.WriteLine() will not work from a WinForms application. 
That’s because the console window that launched WinForms application belongs to the CMD.exe process, which is separate from your WinForms application process.

To dump the Console Output to CMD window, modify the project settings: set application type as Console Application(not Window Application). 

>project properties =>Application =>Output Type =>Console Application.

Then you will get  Windows form and console window and help will be dumped to the CMD window.

An alternative solution, to work on Winform, show the help in popup screen.

**Comment by AntSwift** [comment]
Went with displaying a help form, works great, thanks.
