### ISSUE TITLE
how to use the  Method Dump() for the custom class 

### ISSUE THREAD

**Issue by Tumulalmamun** [commandlineparser/commandline#528]
I am new in using CommandLine Parser. 
From "getting started page" I have tried to run a program.

But Dump is not working for my class.
![image](https://user-images.githubusercontent.com/9098373/67099165-42aac680-f1df-11e9-9b85-17d39d72617b.png)

Thanks in advance.

**Comment by moh-hassan** [comment]
You can use  Nuget package [ObjectDumper.NET](https://www.nuget.org/packages/ObjectDumper.NET)
Dump is used  for demonstration , but you can modify code  to  process/show the values of options.

**Comment by Tumulalmamun** [comment]
Can I get any Video tutorial link.

**Comment by moh-hassan** [comment]
There  is no Video tutorial available.
I hope that wiki with [getting start](https://github.com/commandlineparser/commandline/wiki/Getting-Started) can help.
It include Real life demos that you can practice usage of the library.

**Comment by WimLeflere** [comment]
I find it quite confusing too.
It's in the examples and it works on dotnetfiddle, but when you try it locally it doesn't work.
Maybe add a small remark to the documentation?

**Comment by moh-hassan** [comment]
@WimLeflere 
I have dropped Dump (built-in method in dotnetfiddle.net) and  modified code to use Console.WriteLine

**Comment by henrik-jensen** [comment]
Seems like maybe the issue should be reopened as there still are some places where Dumb is used both in the wiki and on dotnetfiddle.net

Examples (I've found so far):
- [wiki - Getting Started](https://github.com/commandlineparser/commandline/wiki/Getting-Started#method-2)
- [wiki - How To: Q1](https://github.com/commandlineparser/commandline/wiki/How-To#q1)
- [wiki - How To: Q4](https://github.com/commandlineparser/commandline/wiki/How-To#q4)
- wiki - Mutually Exclusive Options - 'Try This' links to dotnetfiddle.net
  - [First Example](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options): [dotnetfiddle.net link](https://dotnetfiddle.net/GeXOFY)
  -  [Best practice](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options#best-practice):  [dotnetfiddle.net link](https://dotnetfiddle.net/uUIfCb)

See also issue #837

PS!  @moh-hassan : He, he,- with inclusion of that Dump method you caught me red handed in [Cargo culting](https://en.wikipedia.org/wiki/Cargo_cult_programming) 😅 

PPS! Think only [Getting Started](https://github.com/commandlineparser/commandline/wiki/Getting-Started#method-2) and [How To](https://github.com/commandlineparser/commandline/wiki/How-To) [Q1](https://github.com/commandlineparser/commandline/wiki/How-To#q1) and [Q4](https://github.com/commandlineparser/commandline/wiki/How-To#q4) uses the `Dump()`method, according to a string search on the wiki sources, but there may still be some "Try It" dotnetfiddle missing. 

PPPS!
Try add this code to both of your above Mutually Exclusive dotnetfiddle examples' `Main()` method (before `...UseCase("not-allowed"...` 
```csharp
...
  UseCase("Should be Mutually Exclusive or should throw an error about missing value to 'documentroot'", "--anonymouslogin --documentroot");
  UseCase("*Is* as expected, Mutually Exclusive", "--anonymouslogin --documentroot ~/var/local/website");
  UseCase("not-allowed", "--enablejavascript --anonymouslogin");
...
```
Seems either a bug with CommandLineParser's Mutually Exclusive functionality or I'm missing some important attributes settings that you have avoided because of briefety reasons. **Edit!** On dotnetfiddle it actually reports an error, but not on the my local maschine with VS2022, CommandLineParser 2.9.1. and a Framework 4.7.2. project. Hmm 🤔?!!
