### ISSUE TITLE
Each command seems to run into a different session!

### ISSUE THREAD

**Issue by SuperJMN** [commandlineparser/commandline#540]
I've ran this code:

```
ssh.RunCommand($"export DISPLAY={options.Display}");
ssh.RunCommand($@"cd ""{options.DestinationPath}""");
ssh.RunCommand($"nohup {options.AssemblyName}");
```

I'm using an export and switching the active directory, but it seems that each command don't affect the next command, for instance, the DISPLAY variable isn't defined, and the current directory doesn't change either.

I've run the exact same commands in an ssh session and it works perfectly. What am I doing wrong? Thanks :)

**Comment by moh-hassan** [comment]
I suppose that you get valid values from  Options and you run these commands from within `WithParsed /MapResult` methods. 

This issue isn't related to CommandLineParser.
I guess that  you are using `ssh.net`.
>I've run the exact same commands in an ssh session and it works perfectly. 

That is correct because all these commands are run in ONE Session.

AS you show in your code you run three different commands in three different sessions and these sessions are not related to each other and The Export path will not effect the next session and so on.

Try to run these commands in one session.

```cs
var command= $"export DISPLAY={options.Display}\n"
  + $@"cd ""{options.DestinationPath}""\n");
  + $"nohup {options.AssemblyName}"
Console.WritLine(command); //  just for debuging  
ssh.RunCommand(command);
```

I suggest validate these commands before executing ssh, e.g., check `DestinationPath` is existing, `Display` in allowed values,...

**Comment by moh-hassan** [comment]
@SuperJMN 
Can you feedback if your issue is resolved?
Thanks

**Comment by SuperJMN** [comment]
I'm sorry! I forgot to answer. Yes, it's fixed. Thanks a lot for your help!!

**Comment by SuperJMN** [comment]
Also, I mistakenly posted the question in the wrong repo. Please, forgive me.

**Comment by moh-hassan** [comment]
Many Thanks @SuperJMN  for your feedback.
