### ISSUE TITLE
An Option of a uint type and non-null default value assigned is always required

### ISSUE THREAD

**Issue by plu83** [commandlineparser/commandline#544]
I encountered a strange issue today involving command line options which makes a parameter required if the associated variable type is a unit and I have a non-null default value assigned.

So for example,
```
[Option("wait-timeout", Default = null, HelpText = "The amount of time in milliseconds to wait for a request to timeout.")]
public uint WaitTimeout { get; set; }
```

Works when the application is executed without the parameter, but setting the Default property to a non-null value suddenly makes it a required parameter.  This behavior does not occur if I set the type to be an int with a non-null Default specified.

**Comment by moh-hassan** [comment]
uint numbers should have suffix u
Instead of the value '123' use '123U'  (suffix: U or u)
U Suffix allows compiler to determine the datatype, check [uint here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types#integer-literals)

This is working fine:
```cs
//set Default 123U or 123u (not 123)
[Option("wait-timeout", Default = 123U, HelpText = "The amount of time in milliseconds to wait for a request to timeout.")]
public uint WaitTimeout { get; set; }
```
Try it [online](https://dotnetfiddle.net/GJqpVA)

**Comment by plu83** [comment]
Thanks for the correction.  I forgot about the explicit suffix and shall close out this ticket.
