### ISSUE TITLE
Value with Whitespace

### ISSUE THREAD

**Issue by Unknow03** [commandlineparser/commandline#741]
For example `myapp "some text"`.
That would be 2 values (`"some` and `text"`).
But i want to have only a single on without quotes: `some text`.
So how can i parse an value with whitespace(s)?

**Comment by rmunn** [comment]
`myapp "some text"` will parse as a single value, `some text` (without quotes), under both Linux and Windows (and also OS X though I don't have a Mac on hand to prove that). If you're seeing it parse as two values, that's a bug, and we'd love to get a bug report. (If you do file a bug report, though, please include **code that will reproduce the bug**, because I'm positive that I won't be able to reproduce it: I've never seen `myapp "some text"` parse as two values, and I don't know how you would manage to make that happen).

**Comment by elgonzo** [comment]
Never have i seen CommandLineParser failing in this way.

I very much suspect this not being the fault of CommandlineParser, because commandline invocations like `myapp "some text" are quite common, and many other users of CommandlineParser would have noticed this issue by now if it were a fault of CommandlineParser.

To me it looks like you haphazardly mess around with or incorrectly create the args string array/enumeration before passing it to the parser, or you are calling myapp from some other script (or from within some other program) that mangles the commandline arguments...

**Comment by czechdude** [comment]
I have the same issue, with 2.2.1.0 and 2.9.0.0 latest preview :( trying to reproduce it.

EDIT: a backslash is ending my string, so it escapes the quote:(
the end result:
 --out "c:\temp\company x\\" 
well, escaping the backslashes before they enter the commandline params is of course a good practice 🤦‍♂️

**Comment by rmunn** [comment]
When trying to reproduce an issue like this, it's often helpful to print out the args being received by your Main() function, *before* CommandLineParser gets hold of them. E.g.,

```cs
    static void Main(string[] args)
    {
        for (int i = 0; i < args.Length; i++)
        {
            Console.WriteLine(String.Format("{0}: ({1})", i, args[i]));
        }
        var result = Parser.Default.ParseArguments<Options>(args);
        // etc.
    }
```

That way you'll be able to tell the difference between "CommandLineParser is mishandling this argument" and "the operating system is doing something I didn't expect with this argument". Also note the parentheses I put around the argument value, so that you can spot any leading or trailing spaces that made it into the argument.

**Comment by znakeeye** [comment]
Removed :P
