### ISSUE TITLE
Covariant issues with Maybe<> on some platforms?  (question)

### ISSUE THREAD

**Issue by svallee-dev** [commandlineparser/commandline#792]
I have an iOS project (Xamarin/VS for Mac) that uses a library, which in turn depend on commandlineparser. 

At runtime I'm getting an exception coming from the command line package:

`Operation is not supported on this platform`

Not sure what it is, I suspect the package may contain CLR codes that are not compatible with my project. So as a test I removed the commandlineparser nuget reference, and added the 2.8.0 source code directly into my project and see if a build error occurs.

And it does. In **TypeConverter.cs** at **line 46** I'm getting this compile error:

`.../Core/TypeConverter.cs(20,20): Error CS0029: Cannot implicitly convert type 'CSharpx.Maybe<RailwaySharp.ErrorHandling.Result<object, System.Exception>>' to 'CSharpx.Maybe<object>' (CS0029)`

It appears there is some kind of covariant typecasting limitation going in my project, but I'm not sure why. Could there be a simple way around this I could do on my side? And if so, would it be a good idea to add it wrapped in a #if build flag in command line parser itself?

**Comment by elgonzo** [comment]
To me, it seems the runtime error you got is unrelated to the compile error.

I don't know what compiler version(s) is (are) being used for Xamarin.IOS in VS on Mac, but the CS0029 error message you got suggests to me that the problem is not about covariance or some such, but rather a sign of the compiler making a mistake when trying to resolve the _ToMaybe_ extension method.

From the error message, it looks like the compiler incorrectly picked:
https://github.com/commandlineparser/commandline/blob/24e2be23ce695d36316d921d2a52f9eb94cb0558/src/CommandLine/Infrastructure/CSharpx/Maybe.cs#L244
instead of the more specific and correct method:
https://github.com/commandlineparser/commandline/blob/24e2be23ce695d36316d921d2a52f9eb94cb0558/src/CommandLine/Infrastructure/ErrorHandling.cs#L654

I have however no idea whether there are newer compiler versions available that would fix that issue, though (as i myself have no experience with Xamarin.IOS and VS on Mac, unfortunately).

As a quick hotfix, you might try changing line 46 in TypeConverter.cs from
```C#
return result.ToMaybe();
```
to
```C#
return ResultExtensions.ToMaybe(result);
```

(As a side note: I am a bit puzzled about the error message quoted in your report referring to line 20 and not line 46. Curious...)

<BR>

With regard to the runtime error "_Operation is not supported on this platform_", note that CommandlineParser 2.8.0 nuget package contains different variations of the library for .NET 4.0, .NET 4.5, .NET 4.61 and .NET Standard 2.0.

Xamarin.IOS supports .NET Standard 2.0 beginning with version 10.14. If by chance your project uses an older Xamarin.IOS version, either try to upgrade to Xamarin.IOS 10.14 or newer, or downgrade to an older CommandlineParser version that supports the platform standard your Xamarin.IOS version is compatible with (for an overview of which Xamarin.IOS version is compatible with which .NET Standard version, see here: https://github.com/dotnet/standard/blob/master/docs/versions.md)

If everything checks out and you then still get the runtime error, double-check whether the correct CommandlineParser library flavour (matching the .NET Standard version your Xamarin.IOS version is compatible with) is being unpacked into your build folder.

**Comment by svallee-dev** [comment]
Thank you so, so much for your reply. As you may have guessed I'm a little over my head trying to figure this one out, and your response contains a multitude of new paths to follows and try.

I'm also confused by the compile error copy/paste. When I look at it in the UI it does say Line 46, and if I double click it it leads me to Line 46. But if I copy/paste it shows line 20 for some reason. 

Maybe as you say this is a Mono compiler bug. But I think I'm using as latest a compiler as Microsoft put in there so who knows. 

In any cases, many thanks again for the super useful reply.

**Comment by svallee-dev** [comment]
Quick update in case someone else encounter the same issue in the future: using elgonzo's suggestion:

`ResultExtensions.ToMaybe(result);`

worked and fixed my compile error. As elgonzo suspected I'm still getting that operation not supported error at runtime, but at least I can debug the source code.

**Comment by svallee-dev** [comment]
Final update: the runtime exception happened in GetWindowWidth() inside ParserSettings.cs, when calling **Console.IsOutputRedirected**. 

It appears my app environment doesn't fully support Console, maybe because it doesn't have a visual console to provide.

It's the only line of code outside the try..catch block... my humble suggestion may be to move it inside the try..catch this way it returns **DefaultMaximumLength** in the edge case scenario like mine?
