### ISSUE TITLE
Question: is this project being maintained?

### ISSUE THREAD

**Issue by mrwensveen** [commandlineparser/commandline#805]
As of this writing, the last commit to this repository was 1.5 years ago. There was a 2.9 preview release and then nothing. Is this project still alive or have the developers moved on to greener pastures?

**Comment by falvarez1** [comment]
And if everyone has moved on then what are the greener pastures being used?

**Comment by elgonzo** [comment]
@falvarez1

There is [System.CommandLine](https://github.com/dotnet/command-line-api).

I find it important to note that the System.CommandLine project is still in beta. It is very close to stabilizing its API (with a stable release or release candidate not that far off, i believe), but it is not 100% stable as of yet. Keep this in mind when you try out System.CommandLine and ponder whether you would want to migrate your existing projects using CommandlineParser right now or wait for a stable release.

Without meaning disrespect to the authors of CommandlineParser and the work they put into the project -- and which is a great library that is immensely valuable for many projects implementing CLIs (and which i considered the go-to library for my CLI-based projects until i came across System.CommandLine), System.CommandLine is both more powerful and versatile than CommandlineParser -- and under active development.

But System.CommandLine is not what i would call a drop-in replacement for CommandlineParser, though. The design philosophy behind System.CommandLine is different from CommandlineParser (for a start, System.CommandLine's definition of CLIs is not based on attribute annotations). It should be technically possible to write something that functions like CommandlineParser and that's using System.Commandline at its core, but that's something you have write either yourself or look for a 3rd-party project that would create such. For simple CLI setups the migration from CommandlineParser to System.Commandline would be trivial, in my opinion, but if you have a project with a somewhat complex CLI using CommandlineParser, however, be prepared to possibly having to spend some elbow grease on the migration.

(I am not affiliated in any way with the System.CommandLine project. Just a developer who one day -- approx. two years ago or so -- found CommandlineParser unsuitable for a more complex CLI setup involving verbs with sub-verbs, iirc, and then found and decided to stick with System.Commandline going forward, despite it not having a stable API yet.)

**Comment by johnjaylward** [comment]
@ericnewton76 , are there any plans on finding a new maintainer for this project?

**Comment by Mario-Hofstaetter** [comment]
After looking at and trying a simple cli app using System.CommandLine I am quite reluctant to use it and find CommandLineParser sytnax far easier to understand.

I just failed to get some easy use cases done there when starting a new app and immediately switched back to CommandLineParser ❤️ But maybe I am just dumb.

**Comment by LostTime76** [comment]
You are not dumb. I have been looking at Cli parsers since .NET was created back in the early days. I just gave System.CommandLine a shot and by jesus is it a complicated beast. It can do so much, yet so little. It's trying to cover every possible usage scenario at the detriment of an easy developer interface. I applaud what the developers have done, but this screams of them being way too clever for their britches. Completely and utterly over engineered and missing basic use cases. So what do they do? They shoe horn another complicated interface in there, because it wasn't designed in up front. 

System.CommandLine is trying to be too clever. It's trying to handle errors and exceptions by itself by spitting technical jargon at the user at times. It's trying to write directly to the console by itself instead of sending me errors of what went wrong so I can handle them in MY code. What if I don't want your stupid "built in" -h, --help, or --version options? What if I wanted to use -h for one of my own options? What if I wanted /h instead? 

"Oh! but you can do those things if you want! You just need to build the entire damn thing yourself using 1000 lines of boilerplate and "builders" and interfaces! See! We built that stuff in!" smfh. 

It never ceases to amaze me how MS developers who are supposed to be highly paid and at the top of their game put the blinders on and just don't see extremely basic use cases. Blows my mind. 20+ years.

**Comment by Mario-Hofstaetter** [comment]
@mrwensveen a new release dropped today even bringing new features to the game 🎉  Nice to see the project is not dead.

**Comment by mrwensveen** [comment]
> @mrwensveen a new release dropped today even bringing new features to the game 🎉 Nice to see the project is not dead.

Awesome, thanks for letting me know 👍

**Comment by znakeeye** [comment]
I actually started off with [System.CommandLine.DragonFruit](https://github.com/dotnet/command-line-api/blob/main/docs/Your-first-app-with-System-CommandLine-DragonFruit.md) then quickly turned to `CommandLineParser`. Nice syntax and **full control**.

I believe `DragonFruit` could _become_ the go-to commandline-parser. Currently it is just too unstable for my needs.
