### ISSUE TITLE
ParseArguments<T> gives CA1812 warning

### ISSUE THREAD

**Issue by znakeeye** [commandlineparser/commandline#816]
Using version `2.8.0`. In projects with `<AnalysisMode>AllEnabledByDefault</AnalysisMode>` set (pretty much recommended for all new projects), the compiler will produce a [CA1812](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1812) warning for this simple case:

```c#
class Options {}

Parser.Default.ParseArguments<Options>(args).WithParsed(Run);
```

Apparently, it cannot know that `Options` will be instantiated. A workaround is to set this ugly attribute to the class:

```c#
[SuppressMessage("Microsoft.Performance", "CA1812", Justification = "Instantiated through reflection")]
class Options {}
```

**Suggestion**
But we can perhaps do better. Can we put a `where T : new()` constraint on the `ParseArguments<T>()` methods? I have verified that this silences the warning!

**Comment by elgonzo** [comment]
> Can we put a where T : new()

No, as this would prevent using option classes with parameterized constructors, such as in this example here: https://github.com/commandlineparser/commandline/wiki#immutable-options-type. But it's probably a hypothetical discussion anyway, at least for now, as the project has not shown any signs of development activity for quite some time. (But then again, since the project seems to be in hiatus with no announcments about a new (beta) version, you might just go ahead, fork the project and apply any changes that benefit your particular coding style with in my opinion little worry to be confronted with a release of a new CommandLineParser version...)

<BR>

> A workaround is to set this ugly attribute to the class:

There is a different way to do this, one that addresses the issue directly (kinda) at the place of origin. Disable the warning using a #pragma directive:
```C#
#pragma warning disable CA1812    // Options classes instantiated through reflection

Parser.Default.ParseArguments<Options>(args).WithParsed(Run);

#pragma warning restore CA1812
```

**Comment by znakeeye** [comment]
Valid points. Closing.
