### ISSUE TITLE
SetValueExceptionError in Unity

### ISSUE THREAD

**Issue by mpattieunity** [commandlineparser/commandline#868]
I'm using the Command line parse in a unity environment and have found that even this most basic use case gives a SetValueExceptionError when trying to resolve my simple set of fake arguments.

According to the debugger, we get a value of "OK: 9" which should be running against Left. But in RuntimePropertyInfo.cs on line 331, it fails because somehow parameters doesn't exist despite being declared just 2 lines earlier.

If I let the debugger keep playing when I have a default value, the default value will follow the same assignment path, but parameters will be found and no error will occur.

As mentioned this code is being called from the Start method of a Unity MonoBehaviour, I don't think that should be relevant.

```using System;
using System.Collections.Generic;
using CommandLine;
using UnityEngine;

public class ArgumentHandler
{
    public class Options
    {
        [Option("left")] public ushort Left { get; set; } // = 1;
        
    }

    public string Result = "Did not parse.";

    private Options _arguments;
    
    public int Left => _arguments.Left;
    
    public ArgumentHandler()
    {
    }


    public void ParseArguments()
    {
        string[] args = Environment.GetCommandLineArgs();

        string[] fakeArgs =
        {
            "--left", "9"
        };

        Parser.Default.ParseArguments<Options>(fakeArgs).WithParsed(RunOptions).WithNotParsed(HandleParseError);
    }

    void RunOptions(Options opts)
    {
        Result = "Parse success";
        _arguments = opts;
    }

    void HandleParseError(IEnumerable<Error> errs)
    {
        Result = "Parse fail";
        foreach (var e in errs)
        {
            Debug.Log($"[{e}]");
        }
    }

}```

**Comment by elgonzo** [comment]
First, make sure you are using the most current version of the library.
Because, with 2.9.1 the code in your question should just work fine (proof: https://dotnetfiddle.net/gd2L3O)
Also, if you still get the exception with 2.9.1, please post the full stack trace of the exception here. (Without the stack trace its difficult to determine where that error really comes from; it might very well be that your problem is entirely unrelated to the CommandLineParser library...)
